//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeaturesRoom
    {
        public int id_features_rooms { get; set; }
        public long id_room { get; set; }
        public int id_feature { get; set; }
        public int deleted { get; set; }
    
        public virtual Feature Feature { get; set; }
        public virtual Room Room { get; set; }
    }
}
