//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public long id_offer { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public double price { get; set; }
        public System.DateTime date_start { get; set; }
        public System.DateTime date_end { get; set; }
        public long room_id { get; set; }
        public long deleted { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
